name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        dotnet-version: ['3.0.x', '7.0.x']
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: ${{ matrix. }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
      